config/routes.rb
Rails.application.routes.draw do

  root :to => 'movies#home'

  get '/movies' => 'movies#index', as: 'movie'
  get '/movies/:id' => 'movies#show', as: 'movie_show'
  post '/movies/:id/watchlist' => 'movies#watchlist', as: 'movie_add_watchlist'
  delete '/movies/:id/watchlist' => 'movies#delete_watchlist', as:'movie_delete_watchlist'

  #####################

  get '/directors/:id' => 'directors#show', as: 'director'

 #########################

  get '/casts/:id' => 'casts#show', as: 'cast'

  ################################

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  
  #######################################

  resources :reviews

  resources :users 
  get '/profile' => 'users#show' 
  get '/profile/ratings' => 'users#index'
  get '/profile/watchlist' => 'users#watch'
  post '/users/:movie_id/watchlist' => 'users#add_to_watchlist', as: 'add_watchlist'
  delete '/users/:movie_id/watchlist' => 'users#delete_from_watchlist', as: 'delete_from_watchlist'
  
 


end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :check_if_logged_in, only: [:watchlist]

  def index

    @movies = Movie.search params[:search]   
    
  end

  def show
    @movie = Movie.find params[:id]
    @movie_cal = @movie.reviews.average(:rating)
  end

  def watchlist
    movie = Movie.find params[:id]

    if @current_user.movies.include? movie
      redirect_to profile_watchlist_path
    else
      @current_user.movies << movie
      redirect_to profile_watchlist_path
    end # current_user.movie.includes?

  end


  def delete_watchlist
    movie = Movie.find params[:id]
    @current_user.movies.delete(movie)
    redirect_to profile_watchlist_path
    
  end 

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/home.html.erb
<script>
    const validateSearch = function(){
        const inputNode = document.querySelector('#search')
        
        if (inputNode.value === ''){
            event.preventDefault()
        }
        
    }
</script>

<div class="home_container">
    <div class="home">

        <h3>Search your movie</h3><br>

        <%= form_tag movie_path, :method => 'get' do %>
            <%= text_field_tag(:search, params[:search], placeholder: "Search by Title" )%>
            <span class="fas fa-search"></span>
            
            <%= button_tag "Search", :class => 'submit', onclick: "validateSearch()" %>
        <% end %>

    </div>
</div>

app/views/movies/index.erb
<div class="index_container">

    <h2>Results for <%= params[:search] %> </h2>

    <hr>
    
    <ul class ="index_ul">
    <% @movies.each do |movie|%>
        <li><%= link_to movie_show_path(movie.id) do %>
            <div class="details">
                <%= image_tag(movie.poster, :class => 'index_image')%>
                <div class="index">
                    <%= movie.title %>
                    (<%= movie.year %>)
                <% end %><br>
                <% movie.casts.each do |c| %>
                    <p id="index_name"><%= c.name %>|</p>
                <% end %>

                </div>
                <% if @current_user.present?%>
                    <% if @current_user.movies.include? movie %>
                        <%= link_to movie_delete_watchlist_path(movie.id), method: 'delete' do %>
                        <i class="fas fa-minus"></i>
                        <% end %>
                        
                    <% else %>
                        <%= link_to movie_add_watchlist_path(movie.id), method: 'POST' do %>
                            <i class="fas fa-plus"></i>

                        <% end %>

                    <% end %>
                <% end %>
                
            </div>

            <hr>
        <% end %>
        </li>
    </ul>

</div>

app/views/movies/show.html.erb
<div class="show_container">

    <% if flash[:error] %>
    <br>
        <div class="error_message">
        <strong>
            <p id = 'login_error_message'><%= flash[:error]  %></p>
        </strong>
        </div>
       
    <% end %>
    <br>

    <%= image_tag @movie.movie_image, :class => 'movie_big_image' %>
    <hr>

    <h2>
    <%= @movie.title %>
    </h2>

    <hr>

    <div class="show_title">
        <p id= "show_text">Poster <br><br>
        <%= image_tag @movie.poster, :class => 'movie_small_image' %>
        </p>

        <p id= "show_text">Trailer<br><br>
        <iframe src='https://www.youtube.com/embed/<%= @movie.trailer %>?rel=0&autoplay=' frameborder='0' allowfullscreen></iframe>
        </p>
    </div>

    <hr>

    <p>
    <strong>Director</strong><br><br>

    <div class="cast_list">
        <div class="cast_list2">
            <%= image_tag(@movie.director.image, :class => 'cast_thumbnail') %>
            <%= link_to @movie.director.name, director_path(@movie.director) %>
        </div>
    </div>
    </p>

    <hr>

    <p>
    <strong>Casts</strong><br><br>
    <div class="cast_list">
        <% @movie.casts.each do |c|%>
            <%= link_to cast_path(c.id) do %>
                <div class="cast_list2">
                    <%= image_tag(c.image, :class => 'cast_thumbnail') %><br>
                    <%= c.name %>
            <% end %>
                </div>
        <% end %>   
    </p>
    </div>

    <hr>

    <h2>Movie Info</h2><br>

    <div class="movie_info">
        <p>
        <strong>Release Year:</strong>
        <%= @movie.year %>
        </p>

        <p>
        <strong>Running Time :</strong>
        <%= @movie.time %>
        </p>

        <p>
        <strong>Rating:</strong>
        <%= @movie.rating %>
        </p>

        <p>
        <strong>User Rating:</strong>
        <%= @movie_cal.to_f %>
        
        </p>

    </div>
    <br>
    <p id ="overview_text">
    <span id="overview">Overview:</span><br>
    <%= @movie.overview %>

    </p>

    <hr>

    <% if @current_user.present? %>
        <div class="add_watchlist">
            <%= link_to add_watchlist_path(@movie.id), id: 'watch_link', method: 'POST' do %>
                <i class="fas fa-plus"></i><br>
                Add to Watchlist
            <% end %>

            <%= link_to '#', id: 'review_link'  do  %>
                <i class="fas fa-pen"></i><br>
                Add review
            <% end %>
        </div>
        <div id ="review_write">
            <%= render partial: 'reviews/form' %>
        </div>
            <% else %>
        <%= link_to 'Log in to write a review', login_path, :class => 'review_login' %>

    <% end %>

    <hr>


    <h2>User reviews</h2>
    <div class="review_content">
    <ul>

        <% @movie.reviews.each do |r|%>
            <li><%= r.content %><br><br>
            <div class="user_review">
                <p><%= cl_image_tag r.user.user_image, :id => 'user_image' %> 
                <span id ="user_rating"><%= r.user.username %></span> 
                | Rating: <span id ="user_rating"> <%= r.rating %></span></p>

                <% if @current_user.present? && r.user_id == @current_user.id %>
                    <p id ="review_edit"><%= link_to 'Edit', edit_review_path(r.id) %>|
                    <%= link_to 'Delete', review_path(r.id), method: 'delete' %></p>
                <% end %>
            </div>
        <hr>
        <% end %>
            </li>
    </ul>
    </div>

</div>