config/routes.rb
Rails.application.routes.draw do

  root :to => 'movies#home'

  get '/movies' => 'movies#index', as: 'movie'
  get '/movies/:id' => 'movies#show', as: 'movie_show'
  post '/movies/:id/watchlist' => 'movies#watchlist', as: 'movie_add_watchlist'
  delete '/movies/:id/watchlist' => 'movies#delete_watchlist', as:'movie_delete_watchlist'

  #####################

  get '/directors/:id' => 'directors#show', as: 'director'

 #########################

  get '/casts/:id' => 'casts#show', as: 'cast'

  ################################

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  
  #######################################

  resources :reviews

  resources :users 
  get '/profile' => 'users#show' 
  get '/profile/ratings' => 'users#index'
  get '/profile/watchlist' => 'users#watch'
  post '/users/:movie_id/watchlist' => 'users#add_to_watchlist', as: 'add_watchlist'
  delete '/users/:movie_id/watchlist' => 'users#delete_from_watchlist', as: 'delete_from_watchlist'
  
 


end

app/models/user.rb
class User < ApplicationRecord


    has_secure_password

    validates :email, :name, :username, presence: true, uniqueness: true

    has_many :reviews
    has_and_belongs_to_many :movies

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_in, except: [:new, :create]


  def new
    @user = User.new
  end

  def create
    @user = User.new user_params 

    if params[:user][:user_image].present?
      # Forward the uploaded image on to Cloudinary (using the gem):
      response = Cloudinary::Uploader.upload params[:user][:user_image]
      p response  # so we can see what the response looks like
      @user.user_image = response['public_id'] # add to the item we are saving
    else 
      @user.user_image = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/271deea8-e28c-41a3-aaf5-2913f5f48be6/de7834s-6515bd40-8b2c-4dc6-a843-5ac1a95a8b55.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI3MWRlZWE4LWUyOGMtNDFhMy1hYWY1LTI5MTNmNWY0OGJlNlwvZGU3ODM0cy02NTE1YmQ0MC04YjJjLTRkYzYtYTg0My01YWMxYTk1YThiNTUuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.BopkDn1ptIwbmcKHdAOlYHyAOOACXW0Zfgbs0-6BY-E'    
    end  # upload check

    @user.save

    if @user.persisted?
      redirect_to login_path
    else
      render :new
    end

  end

  def index
  end

  def show
  end

  def watch
   
    
  end

  def add_to_watchlist
    movie = Movie.find params[:movie_id]
  
    if @current_user.movies.include? movie
      redirect_to movie_show_path(params[:movie_id])
      flash[:error] = 'You have already added this movie in your Watchlist'
    else
      @current_user.movies << movie
      redirect_to profile_watchlist_path
    end # current_user.movie.includes?

  end # add_to_watchlist

  def delete_from_watchlist
    movie = Movie.find params[:movie_id]
    @current_user.movies.delete(movie)
    redirect_to profile_watchlist_path
  end

  def edit
    
  end

  def update

    @current_user = User.find params[:id]

    if params[:user][:user_image].present?
      # Forward the uploaded image on to Cloudinary (using the gem):
      response = Cloudinary::Uploader.upload params[:user][:user_image]
      p response  # so we can see what the response looks like
      @current_user.user_image = response['public_id'] # add to the item we are saving   
    else 
      @current_user.user_image = 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/271deea8-e28c-41a3-aaf5-2913f5f48be6/de7834s-6515bd40-8b2c-4dc6-a843-5ac1a95a8b55.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI3MWRlZWE4LWUyOGMtNDFhMy1hYWY1LTI5MTNmNWY0OGJlNlwvZGU3ODM0cy02NTE1YmQ0MC04YjJjLTRkYzYtYTg0My01YWMxYTk1YThiNTUuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.BopkDn1ptIwbmcKHdAOlYHyAOOACXW0Zfgbs0-6BY-E'
    end  # upload check

    if @current_user.update user_params
      redirect_to profile_path(@current_user)
    else
      render :edit
    end

  end # update

  def destroy
    # @current_user = User.destroy params[:id]
    # redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :username, :password )
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="show_container">

<h2>Edit profile: </h2>
<hr>

<%= form_with model: @current_user, local: true, :html => { multipart: true } do |f| %>

    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
    <br><br>

    <%= f.label :email %>
    <br>
    <%= f.text_field :email %>
    <br><br>

    <%= f.label :username %>
    <br>
    <%= f.text_field :username %>
    <br><br>

    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>
    <br><br>

     <%= f.label 'User Image' %>
    <br>
    <%= f.file_field :user_image, :class => 'file_upload' %>
    <br><br>

    


    <%= f.submit 'Update', :class => 'submit' %>

<% end %>


</div>

app/views/users/index.html.erb
<div class="watch_container">

    <h2>Your Ratings</h2>
    <hr>

    <ul class = "ratings">
    <% @current_user.reviews.each do |r| %>
    <div class="user_ui">
    
        <li><%= link_to image_tag(r.movie.poster), movie_show_path(r.movie.id) %></li>
        <li>
        <p id = "user_review_title">Your review for <%= r.movie.title %></p><br>
        <p id = "user_review_content"><%= r.content %><br><br>
         Your rating: <%= r.rating %></li>

         <p id ="review_edit"><%= link_to 'Edit', edit_review_path(r.id) %><br><%= link_to 'Delete', review_path(r.id), method: 'delete' %></p>
    </div>
         <hr>

    <% end %>

    </ul>
</div>

app/views/users/new.html.erb
<div class = "show_container">

    <h2>Sign up for Search Movies </h2>

    <hr>

<% if @user.errors.any? %>
    <strong> Please correct the following errors: </strong>
    
        <% @user.errors.full_messages.each do |e| %>
        <li>
            <p id = "login_error_message"><%= e %></p>
        </li>
        <% end %>
    
    <hr>
<% end %>

<%= form_with model: @user, local: true, :html => { multipart: true } do |f| %>

    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
    <br><br>

    <%= f.label :email %>
    <br>
    <%= f.text_field :email %>
    <br><br>

    <%= f.label :username %>
    <br>
    <%= f.text_field :username %>
    <br><br>

    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>
    <br><br>

    <%= f.label 'User Image' %>
    <br>
    <%= f.file_field :user_image, :class => 'file_upload' %>
    <br><br>

    


    <%= f.submit 'Sign up', :class => 'submit' %>

<% end %>


</div>

app/views/users/show.html.erb
<div class="show_container">

    <h2>Personal details</h2>
    <hr>

    <div class="profile_detail">

    <%= cl_image_tag @current_user.user_image, :id => 'personal_image' %>
    <p id = "personal_content">
        <span id ="personal_detail">User name </span> <%= @current_user.name %><br>
        <span id ="personal_detail">User email</span> <%= @current_user.email %><br>
        <span id ="personal_detail">User username</span> <%= @current_user.username %>
    </p>

    </div>
    <br>
    <%= link_to 'Edit', edit_user_path(@current_user.id),:class => 'submit' %>

</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/users/watch.html.erb
<div class="watch_container">

    <h2>Your Watchlist</h2>
    <hr>

    <ul class = "watch_list">
        <% @current_user.movies.each do |m| %>
        <div class="watchlist_container">
            <li><%= link_to image_tag(m.poster), movie_show_path(m.id) %></li>
            <li>
            <p id = "watch_title"><%= m.title %></p><br>
                <%= m.year %>
                |
                <%= m.time %>
                |
                <%= m.rating %>
                |<br>
                <%= m.casts.name %>

            <%= m.overview %>
            </li>
            <%= link_to delete_from_watchlist_path(m.id), :class => 'delete_icon', method: 'delete' do %>
            <i class="fas fa-minus"></i>
            <% end %>
        </div>
            <hr>
        <% end %>
    </ul>
</div>