config/routes.rb
Rails.application.routes.draw do

  root :to => 'movies#home'

  get '/movies' => 'movies#index', as: 'movie'
  get '/movies/:id' => 'movies#show', as: 'movie_show'
  post '/movies/:id/watchlist' => 'movies#watchlist', as: 'movie_add_watchlist'
  delete '/movies/:id/watchlist' => 'movies#delete_watchlist', as:'movie_delete_watchlist'

  #####################

  get '/directors/:id' => 'directors#show', as: 'director'

 #########################

  get '/casts/:id' => 'casts#show', as: 'cast'

  ################################

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  
  #######################################

  resources :reviews

  resources :users 
  get '/profile' => 'users#show' 
  get '/profile/ratings' => 'users#index'
  get '/profile/watchlist' => 'users#watch'
  post '/users/:movie_id/watchlist' => 'users#add_to_watchlist', as: 'add_watchlist'
  delete '/users/:movie_id/watchlist' => 'users#delete_from_watchlist', as: 'delete_from_watchlist'
  
 


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

before_action :check_if_logged_in

  def new
  end

  def create
    
    @review = Review.new review_params
    @review.user_id = @current_user.id
    @review.save
    redirect_to movie_show_path(params[:movie_id])

    
  
  end #create

  def index
  end

  def show
  end

  def edit

    @review = Review.find params[:id]
    #checking the user is allowed to edit the review
    redirect_to login_path unless @review.user_id == @current_user.id

  end

  def update
    @review = Review.find params[:id]
    # if the logged in user is not the owner, redirect to login path 
    if @review.user_id != @current_user.id  
      redirect_to login_path
      return
    end #if statement

    @review.update edit_params
    redirect_to movie_show_path(@review.movie_id)

  end #update

  def destroy
    @review = Review.destroy params[:id]
    redirect_to movie_show_path(@review.movie_id)
  end

  private

  def review_params
    params.permit(:content, :rating, :movie_id)

  end

  def edit_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
    <%= form_with url: reviews_path, local: true do |f| %>

        <br>
        
        <%= f.label 'Comment' =%><br>
        <%= f.text_area :content, placeholder: 'What do you think about the movie?', :class => 'review_box' %>
        <br>
        <%= f.label :rating  %><br>
        <%= f.number_field :rating, min: 0, max: 10, step: :any %>
        <br><br>
        <%= f.hidden_field :movie_id, value: params[:id] %>
        <br>
        <br>
        <%= f. submit :class => 'submit' %>

    <% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<div class="show_container">

<h2>Edit reviews</h2>

<hr>

    <%= form_with model: @review, local: true do |f| %>
            
            <br>
            <%= f.text_area :content, :class => 'review_box' %>

            <%= f.hidden_field :movie_id, value: params[:id] %>
            <br>
            <br>

            <%= f.label :rating  %><br>
            <%= f.number_field :rating, min: '0', max: '10'%>
            <br>
            <br>
            <%= f. submit :class => 'submit' %>

        <% end %>

    </div>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>