config/routes.rb
Rails.application.routes.draw do

  root :to => 'movies#home'

  get '/movies' => 'movies#index', as: 'movie'
  get '/movies/:id' => 'movies#show', as: 'movie_show'
  post '/movies/:id/watchlist' => 'movies#watchlist', as: 'movie_add_watchlist'
  delete '/movies/:id/watchlist' => 'movies#delete_watchlist', as:'movie_delete_watchlist'

  #####################

  get '/directors/:id' => 'directors#show', as: 'director'

 #########################

  get '/casts/:id' => 'casts#show', as: 'cast'

  ################################

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  
  #######################################

  resources :reviews

  resources :users 
  get '/profile' => 'users#show' 
  get '/profile/ratings' => 'users#index'
  get '/profile/watchlist' => 'users#watch'
  post '/users/:movie_id/watchlist' => 'users#add_to_watchlist', as: 'add_watchlist'
  delete '/users/:movie_id/watchlist' => 'users#delete_from_watchlist', as: 'delete_from_watchlist'
  
 


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://kit.fontawesome.com/63e0a49b76.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital@1&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@700&display=swap" rel="stylesheet">
    <%= cloudinary_js_config %>

  </head>

  <body>
    <nav class ="navbar">
      <div class="navbar_logo">
        <%= link_to root_path, :class => 'home_link' do %>
        <span class="fas fa-film"></span>
        Search Movies
        <% end %>
      </div>
      <div class="navbar_menu">
        <div class="nav_dropdown">
        <% if @current_user.present? %>
          <%= link_to '#', :class => "nav_font" do %>
            Welcome, <%= @current_user.name %>
          <% end %>
          <div class="dropdown_content">
            <%= link_to 'Profile', profile_path %>
            <%= link_to 'Watchlists', profile_watchlist_path %>
            <%= link_to 'Your ratings', profile_ratings_path %>
          </div>
        </div>
            |
          <%= link_to 'Log out', login_path, method: 'delete', :class => 'home_link' %>
          
          <% else %>
            <%= link_to 'Log in', login_path, :class => 'home_link' %>
            |
            <%= link_to 'Sign up', new_user_path, :class => 'home_link' %>
            
        <% end %>
      </div>
    </nav>
  
    <%= yield %>
  </body>
</html>